export const NONG_EMOTION = {
  GREETING: 'GREETING',
  HAPPY: 'HAPPY',
  ANTICIPATION: 'ANTICIPATION',
  BATH: 'BATH',
  CRY: 'CRY',
  DIE: 'DIE',
  FINISH: 'FINISH',
  FULL: 'FULL',
  TOO_FULL: 'TOO_FULL',
  HELP: 'HELP',
  HUNGRY: 'HUNGRY',
  THINKING: 'THINKING',
  JUMP: 'JUMP',
  KNOCK: 'KNOCK',
  LOVE_DOG: 'LOVE_DOG',
  MASK: 'MASK',
  MUTATE_POOR: 'MUTATE_POOR',
  MUTATE_INSANE: 'MUTATE_INSANE',
  MUTATE: 'MUTATE',
  PLANT: 'PLANT',
  POINT: 'POINT',
  SICK: 'SICK',
  SOMETHING: 'SOMETHING',
  MEH: 'MEH',
  START: 'START',
  STOP: 'STOP',
  TALK_TO_THE_HAND: 'TALK_TO_THE_HAND',
  WAVE: 'WAVE',
};

export const ENVIRONMENT_LEVEL = {
  EXCELLENT: 'EXCELLENT',
  VERY_GOOD: 'VERY_GOOD',
  GOOD: 'GOOD',
  DULL: 'DULL',
  FALLEN: 'FALLEN',
  BAD: 'BAD',
  POLLUTED: 'POLLUTED',
};

export const MENU_LEVEL = {
  HOME: 'HOME',
  PRE_DEFINED: 'PRE_DEFINED',
  CUSTOM: 'CUSTOM',
  WASHING: 'WASHING',
};

export const WASHING_STATE = {
  CONFIG: 'CONFIG',
  START_WASHING: 'START_WASHING',
  WASHING: 'WASHING',
  FINISH_WASHING: 'FINISH_WASHING',
  SUMMARY: 'SUMMARY'
}

export const PROGRAM_TYPE = {
  NORMAL_30: 'NORMAL_30',
  NORMAL_40: 'NORMAL_40',
  NORMAL_60: 'NORMAL_60',
  DELICATE: 'DELICATE',
  HYGIENE: 'HYGIENE',
};
